'use client'
import { useState } from 'react'
import { ParticipantAnswers, WaiverClause, generateClauses } from '@/lib/document-engine'
import Logo           from '@/components/Logo'
import ProgressBar    from '@/components/participant/ProgressBar'
import StepEntry      from '@/components/participant/StepEntry'
import StepIdentity   from '@/components/participant/StepIdentity'
import StepActivity   from '@/components/participant/StepActivity'
import StepHealth     from '@/components/participant/StepHealth'
import { StepGuardian } from '@/components/participant/StepGuardian'
import StepDocument   from '@/components/participant/StepDocument'
import StepSignature  from '@/components/participant/StepSignature'
import StepConfirm    from '@/components/participant/StepConfirm'
import PageNav from '@/components/PageNav'

const ADULT_STEPS = ['Identity','Activity','Health','Review','Sign']
const MINOR_STEPS = ['Identity','Activity','Health','Guardian','Review','Sign']

export default function ParticipantPage() {
  const [step,    setStep]    = useState(0)
  const [answers, setAnswers] = useState<Partial<ParticipantAnswers>>({})
  const [clauses, setClauses] = useState<WaiverClause[]>([])
  const [saving,  setSaving]  = useState(false)

  const isMinor    = answers.isMinor ?? false
  const stepLabels = isMinor ? MINOR_STEPS : ADULT_STEPS

  function next(update?: Partial<ParticipantAnswers>) {
    const merged = { ...answers, ...update }
    setAnswers(merged)
    if (merged.activityKey && merged.fullName) setClauses(generateClauses(merged as ParticipantAnswers))
    const nextStep = step === 3 && !merged.isMinor ? 5 : step + 1
    setStep(nextStep)
  }
  function prev() { setStep(step === 5 && !isMinor ? 3 : Math.max(0, step - 1)) }

  async function handleSign(sigData: string) {
    setSaving(true)
    try {
      const { createClient } = await import('@/lib/supabase')
      const supabase = createClient()
      const full = answers as ParticipantAnswers
      const { data: participant } = await supabase
        .from('participants')
        .upsert({ email:full.email, full_name:full.fullName, dob:full.dob }, { onConflict:'email' })
        .select('id').single()
      if (participant) {
        const { data: session } = await supabase.from('sessions').select('id').limit(1).single()
        if (session) {
          await supabase.from('waivers').insert({
            session_id:session.id, participant_id:participant.id,
            activity_key:full.activityKey, answers:full, clauses,
            signed_at:new Date().toISOString(), signature_data:sigData,
            is_minor:full.isMinor??false, guardian_name:full.guardianName??null,
          })
        }
      }
    } catch (e) { console.error(e) }
    finally { setSaving(false); setStep(7) }
  }

  function restart() { setStep(0); setAnswers({}); setClauses([]) }

  return (
    <div className="min-h-screen bg-surface flex flex-col">
      <PageNav badge="Participant" operatorName="Desert Ridge Adventures" operatorAccent="#4B2ACF" />
      <div className="flex-1 flex flex-col items-center px-4 py-8">
        <div className="w-full max-w-lg">
          {step > 0 && step < 7 && (
            <>
              <div className="flex items-center gap-2 mb-2 text-xs text-muted">
                <span className="font-semibold text-brand tracking-widest uppercase" style={{ letterSpacing:'0.12em' }}>Adaptive waiver</span>
                <span className="text-gray-300">·</span>
                <span>Generated by LIABL Document Intelligence</span>
              </div>
              <ProgressBar steps={stepLabels} current={Math.min(step - 1, stepLabels.length - 1)} />
            </>
          )}
          <div className="animate-fade-up" key={step}>
            {step === 0 && <StepEntry     onNext={() => next()} />}
            {step === 1 && <StepIdentity  onNext={(v) => next(v)} onBack={prev} />}
            {step === 2 && <StepActivity  onNext={(v) => next(v)} onBack={prev} />}
            {step === 3 && <StepHealth    onNext={(v) => next(v)} onBack={prev} answers={answers} />}
            {step === 4 && isMinor && (
              <StepGuardian minorName={answers.fullName ?? 'Minor'}
                onNext={(v) => { setAnswers(a => ({...a,...v})); setStep(5) }}
                onBack={prev} />
            )}
            {step === 5 && <StepDocument  clauses={clauses} answers={answers as ParticipantAnswers} onNext={() => setStep(6)} onBack={prev} />}
            {step === 6 && <StepSignature onSign={handleSign} onBack={prev} saving={saving} />}
            {step === 7 && <StepConfirm   answers={answers as ParticipantAnswers} onRestart={restart} />}
          </div>
        </div>
      </div>
    </div>
  )
}
